<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJvfdR30\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJvfdR30/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJvfdR30.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJvfdR30\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJvfdR30\App_KernelDevDebugContainer([
    'container.build_hash' => 'JvfdR30',
    'container.build_id' => '327bdbb3',
    'container.build_time' => 1576506495,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJvfdR30');
